### ISSUE TITLE
Tapsell in react native >60

### ISSUE THREAD

**Issue by bodaghialib4** [tapsellorg/TapsellSDK-ReactNativeSample#1]
Dear @Ahmadreza-SY 
I am using React Native version 60 and I could not use Tapsell in our new app. 
Is it possible to use Tapsell in RN 60?

**Comment by behdad222** [comment]
@bodaghialib4 
We will fix this problem soon

**Comment by behdad222** [comment]
@bodaghialib4 
The sample project was updated to the latest version of React Native, and Tapsell works without a problem.
Describe your problem.

**Comment by AliA74** [comment]
I also have problem with React Native Version "0.61.2":

` WARN  Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: BannerAdComponent`

Although it works most of the times , but the warning is annoying.

**Comment by bodaghialib4** [comment]
My error related to auto-linking in RN 0.60 and above.

I tried to link tapsell by myself (without auto-linking). for Android, it works but I get below error between the logs of _**reace-native run-android**_ command. 

```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-tapsell (to unlink run: "react-native unlink react-native-tapsell")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

```

But for iOS I could not get a successful run and could not add the SDK file in our project without error (maybe it is because I am not good at iOS native development).
So I disabled tapsell for iOS(with below codes) until I found a correct solution for our problem.

```javascript
//in react-native.config.js file
module.exports = {
    project:{
        ios:{},
        android:{},
    },
    dependencies:{
        "react-native-tapsell": {
            platforms: {
                ios: null
            }
        }
    },
    assets: ['./assets/fonts/'],
};
```

I will be grateful if there is a tutorial or document to help and show me how to add tapsell in RN 0.60 and above (with auto-linking).

ps: Our previous react-native version was 54.4 and I added tapsell in both Android & iOS and it was worked fine.

**Comment by bodaghialib4** [comment]
Dear @behdad222 

today I commented dependencies in react-native.config.js file (disabling link for ios section) and try to link tapsell with

```
react-native link react-native-tapsell
``` 

and I got below error(in iOS):

<img width="352" alt="Screen Shot 1398-08-20 at 10 49 47" src="https://user-images.githubusercontent.com/23075818/68599949-cdb56e80-04b6-11ea-9823-20e1bd92d5df.png">


Am I link this manually or auto-linking?
I will be grateful if you suggest any solution?

**Comment by behdad222** [comment]
@bodaghialib4 @AliA74 
Can you build a sample project?

**Comment by behdad222** [comment]
> Dear @behdad222
> 
> today I commented dependencies in react-native.config.js file (disabling link for ios section) and try to link tapsell with
> 
> ```
> react-native link react-native-tapsell
> ```
> 
> and I got below error(in iOS):
> 
> <img alt="Screen Shot 1398-08-20 at 10 49 47" width="352" src="https://user-images.githubusercontent.com/23075818/68599949-cdb56e80-04b6-11ea-9823-20e1bd92d5df.png">
> 
> Am I link this manually or auto-linking?
> I will be grateful if you suggest any solution?

Tapsell does not have any ads for iOS, I suggest you wait until Tapsell Plus is ready for iOS.

**Comment by bodaghialib4** [comment]
Thanks, I disabled Tapsell for iOS and only used it on the Android platform.
